### ISSUE TITLE
Packages are not available

### ISSUE THREAD

**Issue by jvanz** [kubewarden/seccomp-psp-policy#10]
For some reason, even if our workflow run successfully, the OCI artifact is not published in the github packages.

**Comment by viccuad** [comment]
Now packages are back Oo: https://github.com/kubewarden/seccomp-psp-policy/pkgs/container/policies%2Fseccomp-psp.

Closing.

**Comment by jvanz** [comment]
> Now packages are back Oo: https://github.com/kubewarden/seccomp-psp-policy/pkgs/container/policies%2Fseccomp-psp.
> 
> Closing.

What? How? Have you retrigger a build?

**Comment by viccuad** [comment]
I did trigger a new release workflow, but I'm not sure that's the fix, because for trusted-repos-policy nothing was done.

**Comment by jvanz** [comment]
> I did trigger a new release workflow, but I'm not sure that's the fix, because for trusted-repos-policy nothing was done.
Okay. ;)
